import ThemeButton from '@/components/Theme/ThemeButton'
import Providers from './context/Providers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'LearnU Team-5',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang="en" >
      <body className={`${inter.className} bg-bodyWhite 
      dark:bg-gradient-to-t dark:from-[#0f192c] via-[#1a2544] dark:to-[#1c2e50]`}>
        <Providers>
          <main >
            <ThemeButton />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
