const arr = [
    {
        "__id__": "0fOmAUsDkWX4nRO994Gp",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1rus5qq7aEFMjg-xGHql1Kx6-Pa3h_n_J",
        "description": "Discover the strategies and tactics of effective social media advertising. Gain insights into targeting, content creation, campaign optimization, and measuring results to maximize the impact of your digital marketing efforts. Master the art of reaching and engaging with your target audience through various social media platforms.",
        "duration": 90,
        "id": 23,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1txTOljEyoiT1ZE5eq1uG6ZHP0IV4Xah9",
        "instructorName": "Victoria Campbell",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.4,
        "title": "Social Media Advertising"
    },
    {
        "__id__": "18iZZY5pqmF6JD6vhIpH",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=1wJy6jBfzdrfgxHM8m189LjlZpZ3rqm1E",
        "description": "Explore the practical aspects of the music industry, including copyright, publishing, marketing, and contracts. This course equips aspiring musicians and industry professionals with the knowledge and strategies to navigate the business side of music.",
        "duration": 135,
        "id": 69,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1fpDgbiNYyjvDLmmKL6oLSKFMNRKpG5vz",
        "instructorName": "Leila Kim",
        "isRegistered": "true",
        "isSaved": false,
        "level": "beginner",
        "rating": 4.41,
        "title": "Music Business Essentials"
    },
    {
        "__id__": "2vlh5lD7pqLdcl63Bys6",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1DtiESzQi5lmW2EQgwyYSgYuUEI49nczR",
        "description": " Learn the art of capturing stunning landscapes, mastering composition, lighting, and post-processing techniques to create breathtaking images. Explore the fundamentals of landscape photography, from the equipment you need to the techniques that will help you capture stunning images of the world around you.",
        "duration": 89,
        "id": 55,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1gl7TRobtE3k0KtG2PLxCs4Seg7YvyxHp",
        "instructorName": "William Wright",
        "isRegistered": true,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.91,
        "title": "Landscape Photography"
    },
    {
        "__id__": "3nBHLMQbtJtY1mJEGwnL",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1CTmydf00NeSvdGI1WNP13Vmj9s5taGou",
        "description": "Learn how to develop and execute effective social media marketing strategies to drive growth for your business. Master the art of social media marketing and gain insights into the latest social media marketing trends and best practices to grow your business.",
        "duration": 90,
        "id": 13,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1LzZuhm0w8MyOTGhh2ulXqaQSwkisB5ng",
        "instructorName": "Alexis Reed",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 4.4,
        "title": "Social Media Marketing Strategies"
    },
    {
        "__id__": "4ScpoAdHy6nn3LONaOL5",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=1By59GNM7reQDRXvO_173dlEAMHt9iex6",
        "description": "Learn the fundamentals of data science and gain an understanding of how data science solves real-world problems. Master the basics of data science by understanding the data science process, data wrangling, data exploration, data visualization, and hypothesis building.",
        "duration": 150,
        "id": 9,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1WFNED2yQsnK_aUBOPT0cJ_CdsJd4lv-8",
        "instructorName": "Robert Moore",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.5,
        "title": "Data Science for Beginners"
    },
    {
        "__id__": "4W5zNvjCLRBBmQN2HhjZ",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=1FyOc3IU-Ba_hk1GCxa3vHdlxJ6v-7bNJ",
        "description": "Dive into the world of electronic music production, learning to create beats, melodies, and textures using software and hardware tools. Discover synthesis, sampling, and arrangement techniques to produce your own unique electronic tracks.",
        "duration": 85,
        "id": 68,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1mcVf6inmAzx0yeD57ekdQ-V9DbYq_dZI",
        "instructorName": "Jamal Williams",
        "isRegistered": "true",
        "isSaved": "false",
        "level": "professional",
        "rating": 4.64,
        "title": "Electronic Music Production"
    },
    {
        "__id__": "4fgtOOJRz0EDmgKDq3YV",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1n08UHBuZDZCZdTar8QkwjV9Pg0ViZ2NK",
        "description": "Learn the art of food photography and master the techniques and tips to capture stunning images of food. Explore the fundamentals of food photography, from the equipment you need to the techniques that will help you capture stunning images of food.",
        "duration": 171,
        "id": 58,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1diNBYST3n1zh0KekOzb3zWk8TVXWJnYh",
        "instructorName": "Alexander Scott",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.98,
        "title": "Food Photography"
    },
    {
        "__id__": "5IJK5bC4YbS94OSYetES",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1nn-c0saoViNTfeEIZTzeMQrL-zgG6jMX",
        "description": "Develop a positive mindset that promotes optimism, happiness, and overall well-being. Learn strategies to cultivate gratitude, foster positive thinking, and build habits that enhance your daily life and relationships.",
        "duration": 59,
        "id": 78,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1EU5wTyRWTg_Dapy75AURwMZXb1ES4ocv",
        "instructorName": "Aisha Malik",
        "isRegistered": "true",
        "isSaved": false,
        "level": "intermediate",
        "rating": 3.47,
        "title": "Building A Positive Mindset"
    },
    {
        "__id__": "5zPFYalwGL56QGzb2Vn5",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=1bvMU08DGxbG8uCpulLtE2P08n4wRK7kN",
        "description": "This course focuses on vocal technique, breathing exercises, and performance skills to help you unlock the full potential of your singing voice. Whether you're a beginner or experienced vocalist, you'll learn to refine your technique and enhance your stage presence.",
        "duration": 41,
        "id": 67,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1fY0PUE5ynnn6UI_yDb4dqy9RSyQA-HN-",
        "instructorName": "Fatima Nguyen",
        "isRegistered": "false",
        "isSaved": "true",
        "level": "beginner",
        "rating": 4.27,
        "title": "Vocal Mastery"
    },
    {
        "__id__": "7iFOCc9IqFqSyFhJf1IV",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1jDmeB9eyuQl5Umk3ohXr8eR-xV5fWA5N",
        "description": "Discover effective techniques to set and achieve meaningful goals in various aspects of life. Learn how to create actionable plans, stay motivated, overcome obstacles, and experience a greater sense of fulfillment and success.",
        "duration": 112,
        "id": 80,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1Is1pkn96EpBruR16Y6HEc1-bQcco5tLg",
        "instructorName": "Nate Klein",
        "isRegistered": "true",
        "isSaved": "false",
        "level": "beginner",
        "rating": 3.29,
        "title": "How To Be Successful"
    },
    {
        "__id__": "8t1uqK9pigZzmlQGfMng",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=10zTcqR0SphqhQ6hoNqVZX-LivFPU-Htc",
        "description": "Unlock your creativity and develop your songwriting skills with this course. Dive into the structure, melody, lyrics, and emotional impact of successful songs, and gain practical techniques to write compelling music across genres.",
        "duration": 77,
        "id": 64,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1dFK0vMymfCCCA5-g6hVNm177MNA0Nzoo",
        "instructorName": "Diego Ramirez",
        "isRegistered": "false",
        "isSaved": true,
        "level": "beginner",
        "rating": 4.12,
        "title": "The Art of Songwriting"
    },
    {
        "__id__": "90nE4W5eICJ53HyZxxuu",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1set_EBHJ2uPeIF10NpHh1F9evNn9g1Cw",
        "description": "Unlock your creativity and enhance your design skills by learning key principles, tools, and techniques used by professionals in the field of graphic design. Master the basics of graphic design by understanding the elements and principles of design, typography, and composition.",
        "duration": 90,
        "id": 2,
        "instructorImage": "https://drive.google.com/uc?export=view&id=15PFkwI-4ZkoCkliXDReZqWY4gW0nHuou",
        "instructorName": "Emily Johnson",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.2,
        "title": "Graphic Design Masterclass"
    },
    {
        "__id__": "9jEpX8sRgJyacBW72uuy",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=1GH5SqEsDoeqsA6PZcbOjjthOdz5m-VG5",
        "description": " Learn how to visualize and present complex data using Python libraries, creating impactful and informative visual representations for effective data communication. Master the art of data visualization by understanding the data visualization process, data visualization libraries, and data visualization techniques.",
        "duration": 150,
        "id": 15,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1bPo24BxjkiNCYLrI6i815c4X2S4rZAqO",
        "instructorName": "Laura Thompson",
        "isRegistered": true,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.9,
        "title": "Data Visualization with Python"
    },
    {
        "__id__": "B8etMxCwltEokrfgKp5W",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1jSvNrDnsq7_ACVc7vuLXl2sWBWhAQySv",
        "description": "Gain a deep understanding of user-centric design principles, workflows, and best practices to create intuitive and visually appealing interfaces that enhance user experiences. Master the basics of user interface design by understanding the user interface design process, user interface design principles, and user interface design tools.",
        "duration": 120,
        "id": 30,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1y4IorVUmnX1bBxWWAQAIsjHuxwt2y_OW",
        "instructorName": "Sophia Patel",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.3,
        "title": "User Interface Design"
    },
    {
        "__id__": "CENEBdMOp5q2nTkcBDvs",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1FQUbKn6bo4QR0w8gRdkx7HP1eNWl1dmE",
        "description": "Master the essentials of front-end web development to create responsive and interactive websites that captivate users and gain an understanding of how to build responsive web applications using HTML, CSS, and JavaScript. Master the basics of front-end web development by understanding the front-end web development process, front-end web development tools, and front-end web development techniques.",
        "duration": 180,
        "id": 20,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1q8MWoLW-6JWhy8CZZDedxga6Vwq2PQOl",
        "instructorName": "James Miller",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 4.6,
        "title": "Front-end Web Development"
    },
    {
        "__id__": "DZdkizTXflEcFI7Ocb5E",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=1CWnz4wdl_-p-t8YnX_BpIrszf4Drl_24",
        "description": "Trace the development of music across different eras and genres, from classical to contemporary. Uncover the historical and cultural influences that shaped music, and gain a deeper appreciation for its rich heritage.",
        "duration": 123,
        "id": 66,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1pngWI0-8V_adHEXhjzJa3f2ypcvlrRQL",
        "instructorName": "Omar Patel",
        "isRegistered": "true",
        "isSaved": "true",
        "level": "intermediate",
        "rating": 3.89,
        "title": "Music History Through the Ages"
    },
    {
        "__id__": "DuogXsgLnVn3YpdExGOF",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1uiu_dXrWkYOZQ8c5N1NXrna_B9rR_STH",
        "description": "Learn the fundamentals of entrepreneurship and gain insights into the entrepreneurial mindset, business model development, and the process of starting a business. Master the basics of entrepreneurship by understanding the entrepreneurship process, entrepreneurship tools, and entrepreneurship techniques.",
        "duration": 62,
        "id": 53,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1Aum4KBv-ceDrXwdV7E45elP_h6T-dSQr",
        "instructorName": "James Stewart",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.38,
        "title": "Entrepreneurship 101"
    },
    {
        "__id__": "ECYfRJq6lsxgb7FkmNfG",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1i6h86f0o7GVObVIoNBZNYLfHm4v7Iul2",
        "description": "Discover the art of typography, exploring font selection, hierarchy, spacing, and layout to create visually pleasing and effective typographic designs. Master the basics of typography by understanding the typography process, typography tools, and typography techniques.",
        "duration": 120,
        "id": 24,
        "instructorImage": "https://drive.google.com/uc?export=view&id=17bGUzrfP5rhwfDDVpV-0QES7qpc852CO",
        "instructorName": "Christopher Thompson",
        "isRegistered": false,
        "isSaved": true,
        "level": "beginner",
        "rating": 4.1,
        "title": "Typography Basics"
    },
    {
        "__id__": "Ea5f8zPFeramO7EVWZRi",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1klEO3n2Zo8zRK4zaoDY8pNyBZufUu1hf",
        "description": "Learn practical techniques to manage stress and build resilience in the face of challenges. Discover coping mechanisms, relaxation exercises, and mindfulness practices to enhance your well-being and thrive in a fast-paced world.",
        "duration": 103,
        "id": 74,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1bbqF8o7RZuuq9mn3A61Ok9ILy5yGwAHd",
        "instructorName": "Sema Zilan",
        "isRegistered": "false",
        "isSaved": "true",
        "level": "intermediate",
        "rating": 4.85,
        "title": "Stress Management and Resilience"
    },
    {
        "__id__": "Etk5ODEcCEFg2r1k1Qdb",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=1tFEmDcp3XPj37pYwZMZY8jHIKfqR5L6k",
        "description": "Explore the fascinating world of deep learning and neural networks, diving into the theory and practical implementation of algorithms that mimic the human brain, enabling machines to learn and make complex decisions.",
        "duration": 32,
        "id": 37,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1R6TiWkTVQfP6p-JBShhuZ3RjJddDKzxP",
        "instructorName": "Benjamin Parker",
        "isRegistered": true,
        "isSaved": false,
        "level": "intermediate",
        "rating": 2.98,
        "title": "Deep Learning and Neural Networks"
    },
    {
        "__id__": "FtR85ad0HbARxxOPyqa6",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1KF7dDEGy25ovHFeXWvqGWlIiv3Mg-NFS",
        "description": "Learn essential time management strategies to boost productivity and effectively prioritize tasks. Discover techniques for setting goals, managing distractions, and creating productive routines to achieve a better work-life balance.",
        "duration": 47,
        "id": 73,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1ZdaN4gmxAeGLLH1N69WD6ssH3IulyGWX",
        "instructorName": "Harun Kaya",
        "isRegistered": "true",
        "isSaved": "false",
        "level": "professional",
        "rating": 3.63,
        "title": "Time Management and Productivity"
    },
    {
        "__id__": "G4X4lpC3mbOjq9lqfTR9",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1EXel0-namjgKyWrcuVA29dktMtVLxz5j",
        "description": "Learn the foundations of React.js, a popular JavaScript library for building user interfaces. Discover how to create interactive web applications using components, state management, and other key React concepts.",
        "duration": 180,
        "id": 26,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1LSLT7EazJDV2fD1xqZEAzDzv72wcdjUw",
        "instructorName": "Juan Hernandez",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.7,
        "title": "React.js Fundamentals"
    },
    {
        "__id__": "ISRWUOO9rhizQyzXBZLX",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1phG2Y8m_5V7PiAFa0ycHo9wZtxcdNNQe",
        "description": "Dive into the world of Android app development, gaining hands-on experience in building mobile applications for the Android platform using Java or Kotlin, including UI design, data storage, and device integration. Explore the Android Studio IDE and the Java programming language to build a variety of apps that run on the Android platform.",
        "duration": 152,
        "id": 45,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1CeMFpvGx5dBnxymXqyoIYf9U7-U3YiMk",
        "instructorName": "Lucas Ward",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.12,
        "title": "Android App Development"
    },
    {
        "__id__": "JXsp08ZCyfhw6XuMZ7zM",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1jlLdmWcTEo0SXtBQyDJqBYQZoEldeIu3",
        "description": "Learn techniques to reduce stress, improve focus, and enhance overall well-being. Practice mindfulness and meditation and  develop present-moment awareness and cultivate a calmer mind.",
        "duration": 68,
        "id": 71,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1EQWzc_Tsklo1_3jQ2dI5EtzU5_3wP7yO",
        "instructorName": "Zahra Ahmed",
        "isRegistered": "false",
        "isSaved": "true",
        "level": "beginner",
        "rating": 4.98,
        "title": "Mindfulness and Meditation"
    },
    {
        "__id__": "L1x18HFy98ntn9EV42YJ",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1ZPAp_HPbSV4YOnAve6FQHTIdrpBbql22",
        "description": "Learn the fundamentals of game development, including game design, game programming, and game art. Embark on an exciting journey into the realm of game development, learning key concepts, tools, and workflows to create your own games for various platforms, covering game design, mechanics, and programming.",
        "duration": 127,
        "id": 47,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1xWhEdGmPx_CX9qlBaXcNiQcYimW1QCdT",
        "instructorName": "Daniel Turner",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.9,
        "title": "Introduction to Game Development"
    },
    {
        "__id__": "L6p1v5kbaoGy74cO5qqc",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1e5ek-fLE_HMmW27r7-ccGNEGTRzR3gFT",
        "description": "Master the art of effective email marketing, from crafting engaging content and building subscriber lists to optimizing campaigns and measuring success, to drive engagement and conversions for your business. Gain insights into building email lists, creating valuable content, and creating effective email marketing strategies to grow your business.",
        "duration": 114,
        "id": 32,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1wJXZxdiibWK_8XcINJr5cZ8riN4Cl73b",
        "instructorName": "Jason Kiyoto",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 3.9,
        "title": "Email Marketing Essentials"
    },
    {
        "__id__": "LQqh9KTonwWFd7W5WHkz",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1ynYqjIDGWWjVgi5QSdtjdVnPo7U-qdSh",
        "description": "Delve into the principles and methodologies of user interface (UI) and user experience (UX) design. Learn how to create visually appealing and user-friendly digital experiences through user research, prototyping, and usability testing.",
        "duration": 120,
        "id": 8,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1UTkBRzqQ9b1HVTylWVOJEe1uSXwmpMRL",
        "instructorName": "Jessica Davis",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.4,
        "title": "UI/UX Design Principles"
    },
    {
        "__id__": "MiE6DLINOiyZAhTbFnTx",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1RCe32d9VRK8gmBKhx--McQzqZwY9bLI5",
        "description": " Discover how to build cross-platform mobile applications using React Native, leveraging your existing JavaScript skills to create powerful and native-like experiences for both iOS and Android devices.",
        "duration": 180,
        "id": 16,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1VyuhtceCVeEOFDRHEvxFWJZB9NQYYXoN",
        "instructorName": "Benjamin Clark",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.7,
        "title": "React Native App Development"
    },
    {
        "__id__": "Nc2cEyMdb1Nrg1DsjgiE",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1kh5UvNIL8ThjnR9t7RU5xwjb3AywL6sG",
        "description": "Develop the essential skills and strategies for effective team management, including leadership, communication, conflict resolution, and fostering a collaborative and productive work environment.",
        "duration": 84,
        "id": 51,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1iMcP2UFNZBO03WwiKlUPCVl8hnvyNO2H",
        "instructorName": "Benjamin Rivera",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.7,
        "title": "Effective Team Management"
    },
    {
        "__id__": "NphFPPqLz53SjO5YMOpV",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1F9juFIaEU-nAp0j0iVLzBVSD3F17g_5u",
        "description": "Explore techniques to challenge negative self-talk, develop a positive self-image, and cultivate the belief in your abilities to achieve personal and professional goals.",
        "duration": 74,
        "id": 76,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1ZDR-sxmHVbajtlv6fFkM74eS790wXTSA",
        "instructorName": "Maya Mbeki",
        "isRegistered": "true",
        "isSaved": "true",
        "level": "intermediate",
        "rating": 3.14,
        "title": "Boosting Self Confidence"
    },
    {
        "__id__": "OfncJIab3GZwHyUPzzj4",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1p2-ZU6v9o4op329xd96FtG855WDIHV1v",
        "description": "Learn how to leverage data analysis and visualization techniques to drive informed business decisions. Explore data exploration, statistical analysis, and predictive modeling to extract valuable insights.",
        "duration": 90,
        "id": 11,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1MGgXaBp5FA7wrGPw0F6e-2BWgfDlUVjz",
        "instructorName": "Sophia Martinez",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.3,
        "title": "Business Analytics Essentials"
    },
    {
        "__id__": "OxqhtFNndi3dOG8TtY7N",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=125hPbBijubbtm2Gik1aABTzkwzfa7R5o",
        "description": "Strategies for Marketers: Gain an understanding of search engine optimization (SEO) techniques to improve website visibility and drive organic traffic. Explore keyword research, on-page optimization, link building, and SEO analytics.",
        "duration": 120,
        "id": 17,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1qzX9SgD3j3jPvJ81SgSbNDvcC82z-hzZ",
        "instructorName": "Samantha Phillips",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 4.5,
        "title": "(SEO) Strategies for Marketers"
    },
    {
        "__id__": "PTCHnPUsYpIweOK8fHte",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1YMuHBm2_rlgICGDYgQVpgArqkB_Eu9kN",
        "description": "Develop your emotional intelligence through this course, which explores self-awareness, empathy, and social skills. Learn to navigate emotions effectively, manage conflicts, and build deeper, more meaningful relationships.",
        "duration": 128,
        "id": 79,
        "instructorImage": "https://drive.google.com/uc?export=view&id=179joFM5A_H6scXYbXPZuZU51S1M0fqIw",
        "instructorName": "Mateo Silva",
        "isRegistered": "false",
        "isSaved": "true",
        "level": "beginner",
        "rating": 4.93,
        "title": "Emotional Intelligence"
    },
    {
        "__id__": "Q3qEBrGbKoGbiBc6rFTO",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1uc8etTkPXjf7WRNKdbwPrMji6zYw0Zg5",
        "description": "Uncover the psychological principles behind consumer behavior and decision-making. Learn how to apply these insights to marketing strategies, including persuasion, branding, and creating compelling marketing campaigns.",
        "duration": 120,
        "id": 1,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1qcnMPqJKgqMW9QNGshyp4amMsn3hv9D2",
        "instructorName": "Charlotte Taylor",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.7,
        "title": "Marketing Psychology"
    },
    {
        "__id__": "QRrZmpv4FwABuZCVa5Bf",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1q1LbcXc52rYHGrwmnX_nvxKhaY0PVOK7",
        "description": "Explore the fundamentals of business management, including organizational structures, strategic planning, decision-making, and effective leadership techniques to succeed in the dynamic business world.",
        "duration": 75,
        "id": 5,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1edV5VRK1W_wFK-pKZ2U9nO74UtdQ29zG",
        "instructorName": "Michael Davis",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.1,
        "title": "Introduction to Business Management"
    },
    {
        "__id__": "RMWrOjkBkMB1lkrEsXyo",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1yb4zBEc4KoXCm_5ftktVoWdfR-ZsWMX1",
        "description": "Learn how to craft compelling brand narratives that resonate with audiences, leveraging storytelling techniques to create emotional connections and build strong brand identities.",
        "duration": 48,
        "id": 33,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1WSzj1J-qWutjLJ_UHQE0_pqMiH5zltYO",
        "instructorName": "Serena Miles",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.15,
        "title": "Brand Storytelling"
    },
    {
        "__id__": "SYylxDDtoQr92LMS0nPP",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1Rf8DNB8Ws1KY3eNhg-bpGzEDXxuvK9K_",
        "description": "Dive deeper into search engine optimization strategies, exploring advanced tactics such as keyword research, link building, technical SEO, and analytics to improve website visibility and drive targeted organic traffic.",
        "duration": 90,
        "id": 7,
        "instructorImage": "https://drive.google.com/uc?export=view&id=12se8lH4vf0k7RwbatLMCiRpQU7JxzPMq",
        "instructorName": "Brian Lopez",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 4.8,
        "title": "Advanced SEO Techniques"
    },
    {
        "__id__": "T5omogan3zJxDvk375gq",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1tkD4PUbwnv8oYlPTnammkUC2i_HCdDBn",
        "description": "Immerse yourself in the beauty of nature photography, mastering techniques to capture stunning landscapes, wildlife, and natural elements while understanding composition, lighting, and post-processing to create captivating images.",
        "duration": 120,
        "id": 22,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1cQ1gtAcr7TdPeoXZHa9KB3y-TPwyHqhK",
        "instructorName": "Daniel Parker",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.7,
        "title": "Nature Photography"
    },
    {
        "__id__": "UiZrX7hh18QXXOts8eFi",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=1EUQNF27KVcW-QJ522_F84gye1nl0IrzY",
        "description": "Learn the art of composing music for visual media, understanding the role of music in enhancing storytelling. Explore techniques to create evocative soundtracks, synchronize music with visuals, and collaborate effectively with filmmakers.",
        "duration": 85,
        "id": 70,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1b_AZGVGockpQgisx_SQEVBe4kxvDRPM5",
        "instructorName": "Alejandro Santos",
        "isRegistered": "false",
        "isSaved": "false",
        "level": "intermediate",
        "rating": 3.52,
        "title": "Film Scoring Techniques"
    },
    {
        "__id__": "UmeRtfyAsEg3TpFIDIdB",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1W2IeY23o4B2zwxGu13W5n4a2nhCJgsTL",
        "description": "Explore techniques to overcome creative blocks, ignite inspiration, and nurture your artistic abilities, whether in writing, visual arts, or any other creative endeavor.",
        "duration": 145,
        "id": 77,
        "instructorImage": "https://drive.google.com/uc?export=view&id=16xww_eG6urLzujGM1wbX44ALRodBMl5z",
        "instructorName": "Amara Gupta",
        "isRegistered": "false",
        "isSaved": "true",
        "level": "professional",
        "rating": 4.79,
        "title": "Unlocking Creativity"
    },
    {
        "__id__": "VNqI4E1TNvUiCxp5g8nJ",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1l33g5L8cXdQTCixcWoy84s_kcoR3_Db9",
        "description": "Elevate your photography skills to the next level through a comprehensive masterclass covering various genres, techniques, and creative approaches, honing your abilities to capture impactful and visually striking images.",
        "duration": 220,
        "id": 60,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1mLSY7Y_8q_qP6NZCdkD_Vahrbq6299DS",
        "instructorName": "Henri Cartier",
        "isRegistered": false,
        "isSaved": true,
        "level": "beginner",
        "rating": 4.99,
        "title": "Photography Masterclass"
    },
    {
        "__id__": "Va7wFqY2IDokMAckUAax",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=12TWakarjnzqkkv5pgmdEvQIPZrreLPZr",
        "description": " Delve into statistical methods and techniques used in data science, exploring probability, hypothesis testing, regression, and data modeling to extract meaningful insights and make data-driven decisions.",
        "duration": 149,
        "id": 36,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1JfE8-JRsNTZBrhn0zcv55pNb7JjzyOYw",
        "instructorName": "Emily Johnson",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.12,
        "title": "Statistical Methods for Data Science"
    },
    {
        "__id__": "VzGJnYgDjJ6PA3oX1Tqu",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1knEQsYNMjf6L5Jq1fZHQ81D9qV-OOIcJ",
        "description": "Gain an understanding of cybersecurity threats and vulnerabilities, learning ethical hacking techniques to identify and mitigate security risks, protect systems, and ensure data confidentiality.",
        "duration": 112,
        "id": 48,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1BDLrqpWZ0l8dHN7aL5BkNFKUzRCAERSC",
        "instructorName": "Sophia Mitchell",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 4.89,
        "title": "Ethical Hacking and Cybersecurity"
    },
    {
        "__id__": "WNhaGJuhc38ZhyGQAuLM",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1344jxQK_7DV2xAXQeAZsDZTrtVxd3JhY",
        "description": "Enhance your communication abilities through active listening, nonverbal cues, and assertiveness. Develop skills to express yourself clearly, build meaningful connections, and become a more influential communicator.",
        "duration": 96,
        "id": 72,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1sPW59P5ZSTC_Fstm17gHz5-zVGNU3rIZ",
        "instructorName": "Kofi Abiola",
        "isRegistered": "true",
        "isSaved": "false",
        "level": "beginner",
        "rating": 4.07,
        "title": "Effective Communication Skills"
    },
    {
        "__id__": "YBT1rZYPt1OOfYqnHnCC",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1t_4YO3aDqdxtOgt-AHstkMMLePq6erM9",
        "description": "Acquire the foundational knowledge and skills needed to navigate the entrepreneurial landscape, covering topics such as ideation, market analysis, business models, funding, and growth strategies.",
        "duration": 90,
        "id": 21,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1QpHwRo2NMwv5M_NFX53lj8oMKb3XVGQH",
        "instructorName": "Emma Collins",
        "isRegistered": true,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.2,
        "title": "Entrepreneurship Fundamentals"
    },
    {
        "__id__": "YGcrNw8U4HtXVXA2X3mE",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1S5fa-RDIfsAz-PfIZe8CXCfeTTFzGxtf",
        "description": "Immerse yourself in an intensive bootcamp-style course to learn the essential skills and technologies for web development, including HTML, CSS, JavaScript, and frameworks, to build dynamic and responsive websites.",
        "duration": 150,
        "id": 4,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1b8cNDI8rLyWgDWaJ5R5nXu-grROmkgdt",
        "instructorName": "Sarah Manning",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.5,
        "title": "Web Development Bootcamp"
    },
    {
        "__id__": "YpI83xWKPjReOG8PdNkK",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=16IK6kTpDDL8N5MSkv9XpcSezHbfGtLOm",
        "description": "Embark on a fascinating journey through the cosmos with this introductory astronomy course. Explore celestial objects, the solar system, galaxies, and the mysteries of the universe.",
        "duration": 75,
        "id": 61,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1oT36e0hjVEmaSEYPALdNx6N-ObBphe04",
        "instructorName": "Michael Roberts",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.7,
        "title": "Introduction to Music Theory: A Comprehensive Guide for Beginners"
    },
    {
        "__id__": "ZJz3tMAAVNvaBrE9GmwF",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1xB9gH0TsLtyOBq-Q30osjnwNhK7ww7pq",
        "description": " Deepen your understanding of color principles and psychology, exploring color schemes, harmony, contrast, and the impact of color on design aesthetics and user experiences.",
        "duration": 176,
        "id": 43,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1xXL8oz9voDsVczDswXGwDeNCGvg7NwjU",
        "instructorName": "Samuel Collins",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.87,
        "title": "Color Theory for Designers: A Practical Guide"
    },
    {
        "__id__": "ZQQQn3QB2ZcrRZhizNxB",
        "category": "personal development",
        "courseImage": "https://drive.google.com/uc?export=view&id=16lN0s5Im46GZpjmJk4Dl6lvHJt97x62o",
        "description": "Embrace a growth mindset that fosters a love for learning and personal growth. Explore strategies to overcome challenges, embrace failure as a learning opportunity, and unlock your full potential for lifelong success.",
        "duration": 39,
        "id": 75,
        "instructorImage": "https://drive.google.com/uc?export=view&id=15ZnAna11yp_z0VMTepSsD8b483L6641a",
        "instructorName": "Sofia Castillo",
        "isRegistered": "false",
        "isSaved": "false",
        "level": "beginner",
        "rating": 4.34,
        "title": "Developing A Growth Mindset"
    },
    {
        "__id__": "aQMpa0pozK0LpsPbOVTJ",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1q1hnJ68sHuCHC-EObR57KkPynd_vfnGe",
        "description": "Learn how to create compelling illustrations for design projects, exploring a variety of styles, techniques, and mediums to develop your own unique illustration style.",
        "duration": 90,
        "id": 18,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1WEUqwLNAn5TA8qOcTpcqGnr_rHd-f29r",
        "instructorName": "Henry Roberts",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.3,
        "title": "Illustration for Designers"
    },
    {
        "__id__": "aSAxHwwlDO6lKvynqTTv",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1ta9nR3ak7OfUtSoFBae4CqisAIzksgTC",
        "description": "Discover the power of influencer marketing and learn how to collaborate with influencers to effectively promote products or services, build brand awareness, and reach a targeted audience.",
        "duration": 95,
        "id": 31,
        "instructorImage": "https://drive.google.com/uc?export=view&id=18ftTDq5xhfd2bnDU3P58KYSxm2bt4xW7",
        "instructorName": "Bailey Harrison",
        "isRegistered": true,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.2,
        "title": "Influencer Marketing: Strategies for Effective Partnerships"
    },
    {
        "__id__": "dBmQ3dULtTHO0ZwDx5Zv",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1DPkltoGa9SwACriGpvoJBT27QyIEmmIb",
        "description": "Master the art of capturing compelling portraits, exploring lighting techniques, posing, composition, and post-processing to create stunning and emotive images of people.",
        "duration": 120,
        "id": 12,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1_FpuOW7hquuEgH75j2hF3cgM5knSKOm2",
        "instructorName": "Matthew Baker",
        "isRegistered": true,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.7,
        "title": "Portrait Photography"
    },
    {
        "__id__": "dQR1QCWr7Oy1fDwMkhIT",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1DiLP2jGnz8EjKzOvls1xXucQQ15EN2hq",
        "description": "Dive into the world of photography and learn the essentials, including camera settings, composition, lighting, and editing techniques, to capture captivating images and unleash your creative potential.",
        "duration": 120,
        "id": 6,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1h6lMJG1vZzjOaygA71f1pZNIn25PurzD",
        "instructorName": "Jennifer Wilson",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.6,
        "title": "Photography for Beginners"
    },
    {
        "__id__": "dePED7k2VAJoU5s9vCZg",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1UEz6Qj88emon_GB8NmVPhG6uwQvl8Nqr",
        "description": "Develop a solid foundation in financial management principles, including budgeting, financial analysis, risk management, and investment strategies, to make informed financial decisions for personal or business purposes.",
        "duration": 90,
        "id": 27,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1QdlYOXEPaQ0MHX6XmkH-2LUXC0NF_66v",
        "instructorName": "Andrew Davis",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 4.2,
        "title": "Financial Management"
    },
    {
        "__id__": "eljUKAFW1QIwAAlxSI48",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1krUHrYKJMioUOVCOBjXZqEtfw40R0fKV",
        "description": " Learn the essentials of developing iOS applications, including Swift programming, user interface design, app architecture, and deployment, to create and publish your own iOS apps.",
        "duration": 165,
        "id": 44,
        "instructorImage": "https://drive.google.com/uc?export=view&id=150YiA9HscFJBSXmn3T6PKrCtsww143Md",
        "instructorName": "Mia Price",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.79,
        "title": "iOS App Development"
    },
    {
        "__id__": "gWkXC009AcFEiml6QV4d",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1H3Fa3bp5Uv8eU59sza7bzz9dUixGPQ0f",
        "description": "Gain a comprehensive understanding of financial statements, including balance sheets, income statements, and cash flow statements, and learn how to interpret and analyze them to assess a company's financial health.",
        "duration": 101,
        "id": 49,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1CttpT6gKIVX6a91RDPvefPFu6wPwq6DR",
        "instructorName": "Oliver Cook",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.3,
        "title": "Financial Statements 101"
    },
    {
        "__id__": "geHMW3yDbnVTc2Eif7NY",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=1xPqQCe1k0Riq866nxI4gxJ-xlW8WNbVj",
        "description": "Embark on a fascinating journey through the cosmos with this introductory astronomy course. Explore celestial objects, the solar system, galaxies, and the mysteries of the universe.",
        "duration": 75,
        "id": 62,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1PI9kECwBcJPL4RE8zufSIoUytevsw9Df",
        "instructorName": "Michael Roberts",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.7,
        "title": "Mastering Guitar Techniques: From Beginner to Advanced"
    },
    {
        "__id__": "hHkB13ILbnO8kK2XRJlz",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=1U0_bbG-lq1-i1cNVrF3gSYMGq_PCJy4w",
        "description": "Explore the vast field of big data analytics, learning techniques and tools to process, analyze, and derive insights from large datasets to make data-driven decisions and uncover valuable patterns and trends.",
        "duration": 110,
        "id": 38,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1KNE1-IcW5MBJrRbdXuIhcV07CTm1rWlp",
        "instructorName": "Amelia Evans",
        "isRegistered": false,
        "isSaved": true,
        "level": "intermediate",
        "rating": 3.87,
        "title": "Big Data Analytics"
    },
    {
        "__id__": "hizOrvaMkGnecy7R5hgd",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=1FLNGJYfUgYIwdDMvjw1oj-TinPrRIFDk",
        "description": "Discover the basics of descriptive statistics, including measures of central tendency, variability, and distribution, and learn how to summarize and interpret data using statistical techniques.",
        "duration": 150,
        "id": 25,
        "instructorImage": "https://drive.google.com/uc?export=view&id=189wnznLMk6m3oX0l0zAEDGHCjkrqlDiR",
        "instructorName": "Sophie Walker",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.9,
        "title": "Introduction to Descriptive Statistics"
    },
    {
        "__id__": "i5d8BsSZuEzxQvIjDxyt",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=1jeyK_7PC-gAPnhmUQn1kB8YGA3yoyUoW",
        "description": "Explore the world of music production as you learn to record, edit, and mix your own tracks. From setting up a home studio to utilizing software and hardware, this course equips you with the essentials for producing professional-quality music.",
        "duration": 132,
        "id": 63,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1923Gw5u0smI5bifrxToczBLsWE-RNXOQ",
        "instructorName": "Aisha Khan",
        "isRegistered": "true",
        "isSaved": "false",
        "level": "intermediate",
        "rating": 3.76,
        "title": "Music Production 101: Creating and Recording Your Own Tracks"
    },
    {
        "__id__": "jBus1vjuNV3f8zaG0sJw",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1-Rs-JXGptHafMHSuMFzka-2U4iZaIpMF",
        "description": "Unlock the secrets of capturing stunning images of the night sky, from photographing stars and galaxies to capturing mesmerizing long-exposure shots of celestial phenomena.",
        "duration": 162,
        "id": 59,
        "instructorImage": "https://drive.google.com/uc?export=view&id=13L5_P6u9_WqBKZyg_XhGJHMritkeFH-m",
        "instructorName": "Noah Johannes",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.98,
        "title": "Astrophotography: Capturing the Wonders of the Night Sky"
    },
    {
        "__id__": "kk8J1lFv6cXwSujgQvIQ",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=18mWpx5y8qAtIwe4dTfr1wcT8WsTjyn2K",
        "description": "Learn both frontend and backend web development technologies, including HTML, CSS, JavaScript, server-side programming, and databases, to become a versatile and skilled full stack web developer.",
        "duration": 180,
        "id": 10,
        "instructorImage": "https://drive.google.com/uc?export=view&id=15S3cLXncQzRPKMWcOUdi58uRms601rph",
        "instructorName": "Joseph Bennett",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.6,
        "title": "Full Stack Web Development"
    },
    {
        "__id__": "lAoCqi7FX3bztNlhxpVx",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1ZgIvfOMlSJCicE3NbYoZsgPQwmnOMlwA",
        "description": "Master the art of capturing appealing product images for e-commerce, advertising, or marketing purposes, exploring lighting, styling, composition, and post-processing techniques tailored for product photography.",
        "duration": 184,
        "id": 57,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1REVFcM6r_OWWW83tgjzntOwB_qAsGphN",
        "instructorName": "Daniel Adams",
        "isRegistered": true,
        "isSaved": true,
        "level": "beginner",
        "rating": 4.85,
        "title": "Product Photography 101"
    },
    {
        "__id__": "lMZxgIGkyqmCUeE7vLtg",
        "category": "development",
        "courseImage": "https://drive.google.com/uc?export=view&id=1tZJCz2M5DE6p8Mn4CxL_byNWK93ycIue",
        "description": "Explore the fundamentals of blockchain technology, including decentralized systems, smart contracts, and cryptocurrency development, to understand the potential and applications of blockchain technology.",
        "duration": 138,
        "id": 46,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1_YJODqpiymIHDFprjwwOM_adnvtWGHjy",
        "instructorName": "Ava Reed",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.76,
        "title": "Introduction to Blockchain Development"
    },
    {
        "__id__": "lUmElEmfJjnZOZAnbPAo",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1slC3W6FT-F-PbUCNEDBUXfWD8B1JZymJ",
        "description": "Master the art of studio lighting, from basic setups to advanced techniques, enabling you to create professional-quality photographs in controlled lighting environments.",
        "duration": 195,
        "id": 56,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1iwyqHP3JH2mvckoLYyjkY2R4V_y-S4F-",
        "instructorName": "Emma Lee",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.3,
        "title": "Introduction to Studio Lighting Techniques"
    },
    {
        "__id__": "n1yCG8MZEPvUORsZqyxH",
        "category": "photography",
        "courseImage": "https://drive.google.com/uc?export=view&id=1OUMpU1dSTXfFZstdY-y5l9FmC43rLXNg",
        "description": "Explore the art of capturing authentic and compelling moments in urban environments, learning techniques for composition, storytelling, and capturing the essence of street life.",
        "duration": 120,
        "id": 28,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1hqxLpUztFCm439FJcFwJ_44pESplVG7L",
        "instructorName": "Aya Nakamura",
        "isRegistered": false,
        "isSaved": true,
        "level": "intermediate",
        "rating": 4.6,
        "title": "Street Photography: Documenting Life in the Urban Jungle"
    },
    {
        "__id__": "nisiaZuqu4NV28mb8EXb",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=1kq1i7B0_KEn0__LjN42qScozk7af7t_p",
        "description": "Dive into the world of data mining and pattern recognition, uncovering valuable insights and patterns within large datasets, and developing algorithms for automated data analysis.",
        "duration": 56,
        "id": 39,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1qa3fqD4E7vFNr2cjggvrSMEPeGdVEpCe",
        "instructorName": "Charlotte Evans",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": 4.76,
        "title": "Data Mining and Pattern Recognition"
    },
    {
        "__id__": "nyA5rosTCU5vmgG39bah",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=12J6p3hvE68SzrSB4TjXIgIhP3dzv2JPU",
        "description": "Develop essential leadership skills, including effective communication, decision-making, team management, and inspiring others to achieve organizational goals.",
        "duration": 72,
        "id": 52,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1TBYBICwB0wy1JmB3TR8ePBC3IGwHflsL",
        "instructorName": "Harper Bell",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.9,
        "title": "Leadership Essentials"
    },
    {
        "__id__": "o3Cd4XBLFsziciIUb5fh",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=16dKr34VERdOrSCxYdwWKN_h3gjV27WH2",
        "description": "Learn how to create and implement effective content marketing strategies, including content creation, distribution, engagement, and measuring the success of your campaigns.",
        "duration": 90,
        "id": 29,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1VESjnFYQ3Z0gm_NvfXhixGMWz39yWtwN",
        "instructorName": "Ryan Müller",
        "isRegistered": true,
        "isSaved": true,
        "level": "beginner",
        "rating": 4.4,
        "title": "Content Marketing Strategies"
    },
    {
        "__id__": "plHWxyEw4bXjAp6JkfXW",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=19f5rzA0y1amcVsDV5IdOkBe538b2eyCD",
        "description": "Gain a foundational understanding of data science, including data manipulation, exploratory data analysis, statistical modeling, and data visualization techniques.",
        "duration": 126,
        "id": 35,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1jnZW9kgx8pJG-gLztnU033eNoS2GC6A0",
        "instructorName": "Jennifer Anderson",
        "isRegistered": false,
        "isSaved": true,
        "level": "beginner",
        "rating": 4.8,
        "title": "Introduction to Data Science"
    },
    {
        "__id__": "qjSB9Nj44cETN4InjjhT",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1td9vP_E8hU5_v9inWEVmiweujKoSqwIs",
        "description": "Explore the key principles and strategies for effective supply chain management, including procurement, logistics, inventory management, and supplier relationships.",
        "duration": 158,
        "id": 54,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1jhZJ0J6D1KziVRq-uaRYlYrp0-grvozK",
        "instructorName": "Abigail King",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.9,
        "title": "Supply Chain Management"
    },
    {
        "__id__": "qrkefnFeVO4y3zJ3LF1R",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=13-JfWXbMFFtuCUDJAKsoh_SqpkRV8-rq",
        "description": "Master the essential tools and techniques of Adobe Photoshop, empowering you to edit, retouch, and enhance digital images with precision and creativity.",
        "duration": 78,
        "id": 40,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1iuGZDXTIfFZg6V4ADgAlEWHq7u_8qMsa",
        "instructorName": "Daniel Wilson",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.5,
        "title": "Adobe Photoshop Fundamentals"
    },
    {
        "__id__": "tFsmsKaA0N8M8VEUjfkN",
        "category": "marketing",
        "courseImage": "https://drive.google.com/uc?export=view&id=1DuPnMpmkumKZKNhjh9dGplnnaFXk_0EN",
        "description": "Learn the principles and practices of public relations, including reputation management, media relations, crisis communication, and strategic messaging to effectively promote and protect an organization's image.",
        "duration": 35,
        "id": 34,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1ZdfTmzZu2WfM2GELjZoEPw1-cBEv0tRY",
        "instructorName": "Sam Mikkel",
        "isRegistered": false,
        "isSaved": false,
        "level": "professional",
        "rating": "4.1",
        "title": "Public Relations: Managing Reputation and Relationships"
    },
    {
        "__id__": "uDk9CSOWMllZlt7eNojU",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1D2SW9kWqF9XG850YsHPvC-xLC8jCAk9g",
        "description": "Dive into the world of vector graphics and illustration with Adobe Illustrator, learning essential tools and techniques to create scalable and visually appealing designs.",
        "duration": 198,
        "id": 41,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1rMwFgZvKrSKjMQU0R7DQWC4D3bVDtBp3",
        "instructorName": "Jackson Bennett",
        "isRegistered": true,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.81,
        "title": "Illustrator for Beginners: Creating Vector Graphics"
    },
    {
        "__id__": "vTaImbWNd4HiL59RDa7V",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=18xDwP5O2zOQjEiM0XgJJQGxSnq8gcYIx",
        "description": "Discover how to use Python programming language for data manipulation, analysis, and visualization, gaining the skills needed for data-driven decision-making and machine learning.",
        "duration": 150,
        "id": 19,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1U1oPTAEQne6sRcp5M7cUhmM3UGjp0GWH",
        "instructorName": "Emily Turner",
        "isRegistered": false,
        "isSaved": false,
        "level": "intermediate",
        "rating": 4.8,
        "title": "Python for Data Science"
    },
    {
        "__id__": "wWiqZhataiet8ip7lhTS",
        "category": "music",
        "courseImage": "https://drive.google.com/uc?export=view&id=149Jd3qyybmscgJiHUDfR7k_LSuznLyiB",
        "description": "Delve into the art of improvisation in jazz music. Explore scales, chord progressions, and rhythmic patterns to develop your ability to create captivating solos and improvise with confidence.",
        "duration": 54,
        "id": 65,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1zaCFswSVRm1J8gypWRNTjeUPLcjHe0Y0",
        "instructorName": "Mei Chen",
        "isRegistered": "false",
        "isSaved": "false",
        "level": "professional",
        "rating": 4.53,
        "title": "Jazz Improvisation: Unlocking Your Creative Potential on Any Instrument"
    },
    {
        "__id__": "xZeVFIM11MtpeNDNxtU6",
        "category": "business",
        "courseImage": "https://drive.google.com/uc?export=view&id=1wyqkwRRlma5IgIKN80mRx6bh55asZBTe",
        "description": "Learn the fundamentals of developing a comprehensive business plan, including market research, financial projections, marketing strategies, and operational considerations.",
        "duration": 97,
        "id": 50,
        "instructorImage": "https://drive.google.com/uc?export=view&id=13pNzaxdd2BTgq2aSDJvB8Ye3Ca9h3PcF",
        "instructorName": "Grace Hughes",
        "isRegistered": false,
        "isSaved": true,
        "level": "beginner",
        "rating": 4.2,
        "title": "Business Plan 101"
    },
    {
        "__id__": "zN2x1MjZ6HGSVrH8umCO",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1zZ8FNGRjsgGr8z1fPj-szzkbHto1AG2B",
        "description": "Explore the principles and techniques of effective logo design, including brand identity, typography, color theory, and creating memorable and impactful logos.",
        "duration": 120,
        "id": 14,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1yS8owGQWGeXoykRcdewctulgTDYi-VD0",
        "instructorName": "Andrew Wilson",
        "isRegistered": true,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.1,
        "title": "Logo Design Fundamentals"
    },
    {
        "__id__": "zoj42kV7gGnaCxwSAASm",
        "category": "design",
        "courseImage": "https://drive.google.com/uc?export=view&id=1W1plsPQN05XIfKsE_0iRK6Ij8WFljaLv",
        "description": "Gain a solid foundation in web design principles, including user experience (UX), responsive design, accessibility, and visual aesthetics, to create visually stunning and user-friendly websites.",
        "duration": 187,
        "id": 42,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1tTg_QrhHkXzv6HN9WMxfn7hyMBpAMeXt",
        "instructorName": "Ava Cox",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.9,
        "title": "Web Design Principles"
    },
    {
        "__id__": "zwHNk0EqLYZfWyCPOLJ3",
        "category": "data science",
        "courseImage": "https://drive.google.com/uc?export=view&id=15uck4GH4DC85a2uLRVGbENppNlJJ583U",
        "description": "Dive into the world of machine learning, exploring algorithms, model training, evaluation, and deployment, and understanding how to leverage data to make accurate predictions and automate tasks.",
        "duration": 180,
        "id": 3,
        "instructorImage": "https://drive.google.com/uc?export=view&id=1v3tE97gd5Gi-YP32sbYxEatNYTqVXyfw",
        "instructorName": "David Rodriguez",
        "isRegistered": false,
        "isSaved": false,
        "level": "beginner",
        "rating": 4.9,
        "title": "Machine Learning Fundamentals"
    }
];


function generateCourseModules(courses) {
    const courseModules = [];
  
    courses.forEach((course) => {
      const module1 = {
        moduleId: `${course.id}_module_1`,
        title: `Module 1 Title for ${course.title}`,
        description: `Module 1 Description for ${course.title}`,
        content: `Module 1 content goes here for ${course.title}`,
      };
  
      const module2 = {
        moduleId: `${course.id}_module_2`,
        title: `Module 2 Title for ${course.title}`,
        description: `Module 2 Description for ${course.title}`,
        content: `Module 2 content goes here for ${course.title}`,
      };

      const courseWithModules = {
        moduleID: course.id,
        modules: [module1, module2],
        };
  
      courseModules.push(courseWithModules);
    });
  
    return courseModules;
  }
  
  const courseModules = generateCourseModules(arr);
  console.log(courseModules);