import ThemeButton from '@/components/Theme/ThemeButton';
import Providers from '../context/Providers';
import { NextIntlClientProvider } from 'next-intl';
import './globals.css'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'LearnU Team-5',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'tr' }];
}

export default async function RootLayout({ children, params: { locale } }) {

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.log(error);
  }

  return (
    <html lang={locale}>
      <body className={`${inter.className} bg-bodyWhite dark:bg-gradient-to-t dark:from-[#0f192c] via-[#1a2544] dark:to-[#1c2e50]`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <main>
              <ThemeButton />
              {children}
            </main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}